development:
  stripe_secret_key: 'sk_test_51JZXGxEFRIpd3gukP3AgES3mVqzsO2bAgjoyTAtorFzNzauHrPEjIB47VDYijdmnRQok99C1ShjyYcaUEEOCQRSH00VB7tKfgw'
  stripe_publishable_key: 'pk_test_51JZXGxEFRIpd3guk47bXtdxZabCW5DdFjcl7338HKgSurwuHKMNk1qHj25YU59TVhpfqWeUf0GCL4tm2ith8Trs0001fwQGHb4'

production:
  stripe_secret_key: 'sk_test_51JZXGxEFRIpd3gukP3AgES3mVqzsO2bAgjoyTAtorFzNzauHrPEjIB47VDYijdmnRQok99C1ShjyYcaUEEOCQRSH00VB7tKfgw'
  stripe_publishable_key: 'pk_test_51JZXGxEFRIpd3guk47bXtdxZabCW5DdFjcl7338HKgSurwuHKMNk1qHj25YU59TVhpfqWeUf0GCL4tm2ith8Trs0001fwQGHb4'


